# Use root/example as user/password credentials
version: '3.1'

services:
  mongodb:
    image: mongo
    restart: always
    ports:
      - 27017:27017

  mongo-seed:  
    build: .
    links:
      - mongodb

  mongo-express:
    image: mongo-express
    restart: always
    ports:
      - 8081:8081
    environment:
      ME_CONFIG_MONGODB_SERVER: mongodb
      ME_CONFIG_MONGODB_AUTH_USERNAME: admin
      ME_CONFIG_MONGODB_AUTH_PASSWORD: pass
  
  elasticsearch:  
  image: elasticsearch
  ports:
    - 9200:9200 
    - 9300:9300